// On-disk artifacts produced by sentinel-keygen, plus helpers for writing them
// atomically (write to a temp file, then rename) and with correct permissions.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

// Canonical artifact filenames, relative to the --output directory.
pub const ALLOWLIST: &str = "sentinel.allowlist";
pub const SIGNING_KEY: &str = "sentinel.signing.key";
pub const SIGNING_PUB: &str = "sentinel.signing.pub";
pub const INSTALL_JSON: &str = "sentinel.install.json";
pub const MANIFEST: &str = ".sentinel-keygen-manifest.json";

/// The four secret artifacts an installation is expected to contain. The
/// manifest is deliberately excluded — it is the committed record, not a secret.
pub const SECRET_ARTIFACTS: [&str; 4] = [ALLOWLIST, SIGNING_KEY, SIGNING_PUB, INSTALL_JSON];

pub fn path_in(dir: &Path, name: &str) -> PathBuf {
    dir.join(name)
}

// ── Allowlist (TOML) ────────────────────────────────────────────

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Allowlist {
    #[serde(default)]
    pub agents: Vec<AgentEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentEntry {
    /// SHA-256 of the agent binary, formatted `"sha256:<hex>"`.
    pub binary_hash: String,
    pub binary_path: String,
    /// SHA-256 of the authorizing parent binary (this keygen tool), same format.
    pub parent_hash: String,
    pub description: String,
    pub added_at: String,
}

const ALLOWLIST_HEADER: &str = "\
# Generated by sentinel-keygen. Do not commit. Do not edit manually.
# Add agents via: sentinel-keygen --add-agent
";

impl Allowlist {
    /// Serialize to TOML with the standard do-not-edit header prepended.
    pub fn to_toml(&self) -> Result<String, String> {
        let body = toml::to_string(self)
            .map_err(|e| format!("failed to serialize allowlist: {e}"))?;
        Ok(format!("{ALLOWLIST_HEADER}\n{body}"))
    }

    pub fn from_toml(text: &str) -> Result<Self, String> {
        toml::from_str(text).map_err(|e| format!("allowlist is not valid TOML: {e}"))
    }

    /// Load an existing allowlist, or return an empty one if the file is absent.
    pub fn load_or_empty(path: &Path) -> Result<Self, String> {
        match std::fs::read_to_string(path) {
            Ok(text) => Self::from_toml(&text),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(e) => Err(format!("could not read '{}': {e}", path.display())),
        }
    }
}

// ── Installation record (JSON) ──────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstallRecord {
    pub generated_at: String,
    pub output_path: String,
    pub description: String,
    pub system_identity: String,
    pub key_fingerprint: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rotated_at: Option<String>,
}

// ── Committed manifest (JSON) ───────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub last_run: String,
    pub output_path: String,
    pub artifacts: Vec<String>,
    pub key_fingerprint: String,
    pub description: String,
}

// ── Atomic writes ───────────────────────────────────────────────

/// Write `contents` to `path` atomically: write to a sibling temp file, then
/// rename over the destination. `mode` (Unix permission bits) is applied to the
/// temp file before the rename so the final file never exists with wider perms.
pub fn atomic_write(path: &Path, contents: &[u8], mode: Option<u32>) -> Result<(), String> {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let file_name = path
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| format!("invalid output path '{}'", path.display()))?;
    // A pid-suffixed temp name in the same directory keeps the rename atomic
    // (same filesystem) and avoids clashing with the live file.
    let tmp = dir.join(format!(".{file_name}.tmp.{}", std::process::id()));

    let write_result = (|| -> std::io::Result<()> {
        std::fs::write(&tmp, contents)?;
        #[cfg(unix)]
        if let Some(bits) = mode {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(bits))?;
        }
        #[cfg(not(unix))]
        let _ = mode;
        std::fs::rename(&tmp, path)
    })();

    if let Err(e) = write_result {
        let _ = std::fs::remove_file(&tmp); // best-effort cleanup
        return Err(format!("failed to write '{}': {e}", path.display()));
    }
    Ok(())
}

pub fn write_json<T: Serialize>(path: &Path, value: &T, mode: Option<u32>) -> Result<(), String> {
    let json = serde_json::to_string_pretty(value)
        .map_err(|e| format!("failed to serialize JSON for '{}': {e}", path.display()))?;
    atomic_write(path, json.as_bytes(), mode)
}
