// Cryptographic primitives for sentinel-keygen.
//
// The Sentinel workspace ships no Rust signing crate (no ed25519/ring/etc. in
// the lockfile), so per the build constraints we DO NOT invent a primitive:
// signing keypairs are generated by shelling out to the system `openssl`.
//
// Algorithm: EC P-256 (prime256v1). Chosen for portability — it is supported by
// both OpenSSL and LibreSSL (the latter ships on macOS and does not support
// `genpkey -algorithm ed25519`). Hashing is done in-process with the `sha2`
// crate that sentinel-types already depends on.

use sha2::{Digest, Sha256};
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

/// The all-zero hash, used when a value cannot be determined (e.g. parent
/// binary could not be located). Matches the `sha256:<64 hex>` field format.
pub const ZERO_HASH: &str = "sha256:0000000000000000000000000000000000000000000000000000000000000000";

/// A freshly generated signing keypair, held in memory as PEM text so the
/// caller can write both files atomically with the correct permissions.
pub struct Keypair {
    pub private_pem: Vec<u8>,
    pub public_pem: Vec<u8>,
}

/// Compute SHA-256 over a file's raw bytes and return it as `"sha256:<hex>"`.
pub fn hash_file(path: &Path) -> Result<String, String> {
    let bytes = std::fs::read(path)
        .map_err(|e| format!("could not read '{}': {e}", path.display()))?;
    Ok(hash_bytes(&bytes))
}

/// Compute SHA-256 over raw bytes and return it as `"sha256:<hex>"`.
pub fn hash_bytes(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("sha256:{}", hex::encode(hasher.finalize()))
}

/// Generate a new EC P-256 signing keypair by shelling out to `openssl`.
pub fn generate_keypair() -> Result<Keypair, String> {
    // Private key -> stdout as PEM.
    let private_pem = run_openssl(
        &["ecparam", "-name", "prime256v1", "-genkey", "-noout"],
        None,
    )?;
    // Derive the public key from the private key piped in on stdin.
    let public_pem = run_openssl(&["ec", "-pubout"], Some(&private_pem))?;
    Ok(Keypair { private_pem, public_pem })
}

/// Run `openssl <args>`, optionally feeding `stdin`, returning captured stdout.
/// openssl writes progress noise ("read EC key") to stderr, which we discard.
fn run_openssl(args: &[&str], stdin: Option<&[u8]>) -> Result<Vec<u8>, String> {
    let mut cmd = Command::new("openssl");
    cmd.args(args)
        .stdin(if stdin.is_some() { Stdio::piped() } else { Stdio::null() })
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    let mut child = cmd.spawn().map_err(|e| {
        format!(
            "could not run 'openssl' (is it installed and on PATH?): {e}\n\
             sentinel-keygen relies on the system openssl to generate signing keys."
        )
    })?;

    if let Some(data) = stdin {
        child
            .stdin
            .take()
            .ok_or("failed to open stdin for openssl")?
            .write_all(data)
            .map_err(|e| format!("failed to write to openssl stdin: {e}"))?;
    }

    let out = child
        .wait_with_output()
        .map_err(|e| format!("openssl did not complete: {e}"))?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(format!(
            "openssl {} failed: {}",
            args.join(" "),
            stderr.trim()
        ));
    }
    Ok(out.stdout)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hash_bytes_is_prefixed_64_hex() {
        let h = hash_bytes(b"hello");
        assert!(h.starts_with("sha256:"));
        assert_eq!(h.len(), "sha256:".len() + 64);
        // Known SHA-256 of "hello".
        assert_eq!(
            h,
            "sha256:2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }

    #[test]
    fn zero_hash_is_well_formed() {
        assert!(ZERO_HASH.starts_with("sha256:"));
        assert_eq!(ZERO_HASH.len(), "sha256:".len() + 64);
    }
}
